### ISSUE TITLE
用 css grid 排版月曆布局 A Calendar in Three Lines of CSS | CSS-Tricks

### ISSUE THREAD

**Issue by ayugioh2003** [ayugioh2003/today-i-learned#1096]
## 網址
- [卡斯伯 - 貼文 | Facebook](https://www.facebook.com/WccCasper/posts/1201317096931178)
- [A Calendar in Three Lines of CSS | CSS-Tricks](https://css-tricks.com/a-calendar-in-three-lines-of-css/)
- [A Calendar in Three Lines of CSS – Calendar Tricks](https://calendartricks.com/a-calendar-in-three-lines-of-css/)

## 觀念
```html
<div class="calendar-wrapper">
  <h1>Decemeber</h1>
  <ul class="calendar">
    <li class="weekday">Sun</li>
    <li class="weekday">Mon</li>
    <li class="weekday">Tue</li>
    <li class="weekday">Wed</li>
    <li class="weekday">Thu</li>
    <li class="weekday">Fri</li>
    <li class="weekday">Sat</li>

    <li class="first-day">1</li>
    <li>2</li>
    <li>3</li>
    <!-- ... -->
    <li>29</li>
    <li>30</li>
    <li>31</li>
  </ul>
</div>
```

```css
.calendar {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
}
.first-day {
  grid-column-start: 3;
}

```
