### ISSUE TITLE
How to Make a Landing Page using HTML, SCSS, and JavaScript - Full Course  登入頁切板 demo

### ISSUE THREAD

**Issue by ayugioh2003** [ayugioh2003/today-i-learned#1136]
## 網址
- [(1277) How to Make a Landing Page using HTML, SCSS, and JavaScript - Full Course - YouTube](https://www.youtube.com/watch?v=aoQ6S1a32j8&ab_channel=freeCodeCamp.org)
- [thecodercoder/fem-easybank: Easybank landing page from Frontend Mentor](https://github.com/thecodercoder/fem-easybank)
- [Frontend Mentor | Easybank landing page coding challenge](https://www.frontendmentor.io/challenges/easybank-landing-page-WaUhkoDN)0

## 觀念
color 管理
- [Sass map get | 卡斯伯 Blog - 前端，沒有極限](https://wcc723.github.io/sass/2015/02/11/sass-map-get/)
- [SASS : SASS Maps - get、merge、remove - iT 邦幫忙::一起幫忙解決難題，拯救 IT 人的一天](https://ithelp.ithome.com.tw/articles/10207093)
- [Sass教學 (40) - 使用Sass Maps提升程式可讀、變數群組性 - iT 邦幫忙::一起幫忙解決難題，拯救 IT 人的一天](https://ithelp.ithome.com.tw/articles/10161389)
- [你可能不知道的 Sass 技巧. 我發現有許多前端工程師只把 sass 當作有變數、nested class 跟… | by 愷開 | De-Magazine | Medium](https://medium.com/d-d-mag/%E4%BD%A0%E5%8F%AF%E8%83%BD%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84-sass-%E6%8A%80%E5%B7%A7-c97d4d5e0fc4)

font 管理

media query 管理
```scss
// _mixins.scss
$breakpoints-up: (
  "medium": "40em",
  "large": "64em",
  "xlarge" "87.5em"
)

@mixin breakpoint-up($size) {
  @media (min-width: map-get($breakpoints-up, $size)) {
    @content;
  }
}
```

```scss
// _hero.scss
@include breakpoint-up(large) {
  display: flex;
  align-items: center;
}
```

animate
