### ISSUE TITLE
vue cli + eslint + prettier 設定

### ISSUE THREAD

**Issue by ayugioh2003** [ayugioh2003/today-i-learned#194]
## 記錄原因

每次用 vue cli 建專案時，總需要微調 eslint 和 prettier 設定。想說做個記錄一下

## 學習點
安裝相關開發套件
vetur, eslint, prettier
關閉 vetur 設定，prettier 微調

用 vue cli 建立專案
要選 eslint 選項，我平常選 standard
```vue create demo
```

安裝 package
prettier, @vue/prettier

微調 eslint, prettier 設定
```yaml
# prettierrc.yaml
# printWidth: 80
tabWidth: 2
semi: false
singleQuote: true
# trailingComma: 'es5'
# bracketSpacing: true
arrowParens: 'avoid'
```

微調 eslintrc.js
```js
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: ['plugin:vue/essential', '@vue/standard'],
  parserOptions: {
    parser: 'babel-eslint'
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'space-before-function-paren': ['error', 'never']
  }
}
```

vscode 設定檔
`"editor.formatOnSave": true`

## 相關資料
* [vue.js - How to configure Vue CLI 4 with ESLint + Prettier + Airbnb rules + TypeScript + Vetur? - Stack Overflow](https://stackoverflow.com/questions/58670850/how-to-configure-vue-cli-4-with-eslint-prettier-airbnb-rules-typescript)
* [[Vue] 整合 Vue style guide, eslint-plugin-vue 和 VSCode ~ PJCHENder<br > 那些沒告訴你的小細節](https://pjchender.blogspot.com/2019/07/vue-vue-style-guide-eslint-plugin-vue.html)
* [ESLint - Pluggable JavaScript linter](https://eslint.org/)
* [Options · Prettier](https://prettier.io/docs/en/options.html)

**Comment by ayugioh2003** [comment]
airbnb
```yaml
# prettierrc.yaml
# printWidth: 80
tabWidth: 2
# semi: false
singleQuote: true
trailingComma: 'es5'
# bracketSpacing: true
arrowParens: 'always' # 'avoid'
```
